# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 736)
        MainWindow.setToolTipDuration(3)
        MainWindow.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(94, 94, 94);\n"
"border-color: rgb(70, 70, 70);")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setGeometry(QtCore.QRect(50, 150, 1266, 151))
        font = QtGui.QFont()
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTipDuration(0)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabBar::tab{ \n"
"height: 50px; width:146px; \n"
"background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);\n"
"border-width: 3px;\n"
"    border-color: rgb(76, 76, 76);\n"
"border-style: solid;\n"
"border-radius: 0;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"}\n"
"\n"
"QTabBar::tab:hover{\n"
"    border-top-color: #1D2A32;\n"
"    border-color: #40494E;\n"
"    color: black;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #C1D8E8, stop: 1 #F0F5F8); \n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"         background-color: rgb(255, 185, 185);\n"
" }\n"
"\n"
"QTabBar { background: transparent; \n"
"border-width: 5px;\n"
"border-color: rgb(255, 255, 255);\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setKerning(True)
        self.tab_1.setFont(font)
        self.tab_1.setAutoFillBackground(False)
        self.tab_1.setObjectName("tab_1")
        self.widget = QtWidgets.QWidget(self.tab_1)
        self.widget.setGeometry(QtCore.QRect(50, 30, 1166, 30))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.widget.setObjectName("widget")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setGeometry(QtCore.QRect(50, 50, 1166, 30))
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.widget_2.setObjectName("widget_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(470, 85, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget_3 = QtWidgets.QWidget(self.tab_3)
        self.widget_3.setGeometry(QtCore.QRect(50, 50, 1166, 30))
        self.widget_3.setAutoFillBackground(False)
        self.widget_3.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.widget_3.setObjectName("widget_3")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(470, 85, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_4 = QtWidgets.QWidget(self.tab_4)
        self.widget_4.setGeometry(QtCore.QRect(50, 50, 1166, 30))
        self.widget_4.setAutoFillBackground(False)
        self.widget_4.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.widget_4.setObjectName("widget_4")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(470, 85, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_5 = QtWidgets.QWidget(self.tab_5)
        self.widget_5.setGeometry(QtCore.QRect(50, 50, 1166, 30))
        self.widget_5.setAutoFillBackground(False)
        self.widget_5.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.widget_5.setObjectName("widget_5")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(470, 85, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.widget_6 = QtWidgets.QWidget(self.tab_6)
        self.widget_6.setGeometry(QtCore.QRect(50, 50, 1166, 30))
        self.widget_6.setAutoFillBackground(False)
        self.widget_6.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.widget_6.setObjectName("widget_6")
        self.label_10 = QtWidgets.QLabel(self.tab_6)
        self.label_10.setGeometry(QtCore.QRect(470, 85, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.widget_7 = QtWidgets.QWidget(self.tab_7)
        self.widget_7.setGeometry(QtCore.QRect(50, 50, 1166, 30))
        self.widget_7.setAutoFillBackground(False)
        self.widget_7.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.widget_7.setObjectName("widget_7")
        self.label_11 = QtWidgets.QLabel(self.tab_7)
        self.label_11.setGeometry(QtCore.QRect(470, 85, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.widget_8 = QtWidgets.QWidget(self.tab_8)
        self.widget_8.setGeometry(QtCore.QRect(50, 50, 1166, 30))
        self.widget_8.setAutoFillBackground(False)
        self.widget_8.setStyleSheet("background-color: rgb(181, 181, 181);")
        self.widget_8.setObjectName("widget_8")
        self.label_12 = QtWidgets.QLabel(self.tab_8)
        self.label_12.setGeometry(QtCore.QRect(470, 85, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab_8, "")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 10, 511, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.getAnzahlKlemmen = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.getAnzahlKlemmen.setFont(font)
        self.getAnzahlKlemmen.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);")
        self.getAnzahlKlemmen.setObjectName("getAnzahlKlemmen")
        self.gridLayout_2.addWidget(self.getAnzahlKlemmen, 0, 1, 1, 1)
        self.maxKlemmenHutschiene = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.maxKlemmenHutschiene.setFont(font)
        self.maxKlemmenHutschiene.setObjectName("maxKlemmenHutschiene")
        self.gridLayout_2.addWidget(self.maxKlemmenHutschiene, 2, 0, 1, 1)
        self.getMaxKlemmenHutschiene = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.getMaxKlemmenHutschiene.setFont(font)
        self.getMaxKlemmenHutschiene.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);")
        self.getMaxKlemmenHutschiene.setObjectName("getMaxKlemmenHutschiene")
        self.gridLayout_2.addWidget(self.getMaxKlemmenHutschiene, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.getAnzahlHutschienen = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.getAnzahlHutschienen.setFont(font)
        self.getAnzahlHutschienen.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);")
        self.getAnzahlHutschienen.setObjectName("getAnzahlHutschienen")
        self.gridLayout_2.addWidget(self.getAnzahlHutschienen, 1, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(50, 320, 1261, 111))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.AnzahlKlemme3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AnzahlKlemme3.setFont(font)
        self.AnzahlKlemme3.setObjectName("AnzahlKlemme3")
        self.gridLayout_3.addWidget(self.AnzahlKlemme3, 3, 0, 1, 1)
        self.setAnzahlKlemme6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setAnzahlKlemme6.setFont(font)
        self.setAnzahlKlemme6.setObjectName("setAnzahlKlemme6")
        self.gridLayout_3.addWidget(self.setAnzahlKlemme6, 3, 3, 1, 1)
        self.setAnzahlKlemme1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setAnzahlKlemme1.setFont(font)
        self.setAnzahlKlemme1.setObjectName("setAnzahlKlemme1")
        self.gridLayout_3.addWidget(self.setAnzahlKlemme1, 1, 1, 1, 1)
        self.setAnzahlKlemme4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setAnzahlKlemme4.setFont(font)
        self.setAnzahlKlemme4.setObjectName("setAnzahlKlemme4")
        self.gridLayout_3.addWidget(self.setAnzahlKlemme4, 1, 3, 1, 1)
        self.AnzahlKlemme4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AnzahlKlemme4.setFont(font)
        self.AnzahlKlemme4.setObjectName("AnzahlKlemme4")
        self.gridLayout_3.addWidget(self.AnzahlKlemme4, 1, 2, 1, 1)
        self.AnzahlKlemme2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AnzahlKlemme2.setFont(font)
        self.AnzahlKlemme2.setObjectName("AnzahlKlemme2")
        self.gridLayout_3.addWidget(self.AnzahlKlemme2, 2, 0, 1, 1)
        self.setAnzahlKlemme5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setAnzahlKlemme5.setFont(font)
        self.setAnzahlKlemme5.setObjectName("setAnzahlKlemme5")
        self.gridLayout_3.addWidget(self.setAnzahlKlemme5, 2, 3, 1, 1)
        self.setAnzahlKlemme3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setAnzahlKlemme3.setFont(font)
        self.setAnzahlKlemme3.setObjectName("setAnzahlKlemme3")
        self.gridLayout_3.addWidget(self.setAnzahlKlemme3, 3, 1, 1, 1)
        self.AnzahlKlemme6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AnzahlKlemme6.setFont(font)
        self.AnzahlKlemme6.setObjectName("AnzahlKlemme6")
        self.gridLayout_3.addWidget(self.AnzahlKlemme6, 3, 2, 1, 1)
        self.AnzahlKlemme5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AnzahlKlemme5.setFont(font)
        self.AnzahlKlemme5.setObjectName("AnzahlKlemme5")
        self.gridLayout_3.addWidget(self.AnzahlKlemme5, 2, 2, 1, 1)
        self.setAnzahlKlemme2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setAnzahlKlemme2.setFont(font)
        self.setAnzahlKlemme2.setObjectName("setAnzahlKlemme2")
        self.gridLayout_3.addWidget(self.setAnzahlKlemme2, 2, 1, 1, 1)
        self.AnzahlKlemme1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AnzahlKlemme1.setFont(font)
        self.AnzahlKlemme1.setObjectName("AnzahlKlemme1")
        self.gridLayout_3.addWidget(self.AnzahlKlemme1, 1, 0, 1, 1)
        self.AnzahlGesamt = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AnzahlGesamt.setFont(font)
        self.AnzahlGesamt.setObjectName("AnzahlGesamt")
        self.gridLayout_3.addWidget(self.AnzahlGesamt, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 3, 1, 1)
        self.setAnzahlGesamt = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setAnzahlGesamt.setFont(font)
        self.setAnzahlGesamt.setObjectName("setAnzahlGesamt")
        self.gridLayout_3.addWidget(self.setAnzahlGesamt, 0, 1, 1, 1)
        self.Klemme1 = QtWidgets.QPushButton(self.centralwidget)
        self.Klemme1.setEnabled(False)
        self.Klemme1.setGeometry(QtCore.QRect(40, 450, 416, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Klemme1.setFont(font)
        self.Klemme1.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.00558659 rgba(59, 59, 59, 255), stop:1 rgba(166, 166, 166, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 15;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 400px;\n"
"max-width: 400px;\n"
"min-height: 44px;\n"
"max-height: 44px;\n"
"}")
        self.Klemme1.setObjectName("Klemme1")
        self.Klemme2 = QtWidgets.QPushButton(self.centralwidget)
        self.Klemme2.setEnabled(False)
        self.Klemme2.setGeometry(QtCore.QRect(470, 450, 416, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Klemme2.setFont(font)
        self.Klemme2.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.00558659 rgba(59, 59, 59, 255), stop:1 rgba(166, 166, 166, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 15;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 400px;\n"
"max-width: 400px;\n"
"min-height: 44px;\n"
"max-height: 44px;\n"
"}")
        self.Klemme2.setObjectName("Klemme2")
        self.Klemme3 = QtWidgets.QPushButton(self.centralwidget)
        self.Klemme3.setEnabled(False)
        self.Klemme3.setGeometry(QtCore.QRect(900, 450, 416, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Klemme3.setFont(font)
        self.Klemme3.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.00558659 rgba(59, 59, 59, 255), stop:1 rgba(166, 166, 166, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 15;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 400px;\n"
"max-width: 400px;\n"
"min-height: 44px;\n"
"max-height: 44px;\n"
"}")
        self.Klemme3.setObjectName("Klemme3")
        self.Klemme4 = QtWidgets.QPushButton(self.centralwidget)
        self.Klemme4.setEnabled(False)
        self.Klemme4.setGeometry(QtCore.QRect(40, 530, 416, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Klemme4.setFont(font)
        self.Klemme4.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.134 rgba(7, 255, 44, 255), stop:0.608939 rgba(255, 241, 87, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 15;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 400px;\n"
"max-width: 400px;\n"
"min-height: 44px;\n"
"max-height: 44\n"
"px;\n"
"}")
        self.Klemme4.setObjectName("Klemme4")
        self.Klemme5 = QtWidgets.QPushButton(self.centralwidget)
        self.Klemme5.setEnabled(False)
        self.Klemme5.setGeometry(QtCore.QRect(470, 530, 416, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Klemme5.setFont(font)
        self.Klemme5.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.134 rgba(7, 255, 44, 255), stop:0.608939 rgba(255, 241, 87, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 15;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 400px;\n"
"max-width: 400px;\n"
"min-height: 44px;\n"
"max-height: 44\n"
"px;\n"
"}")
        self.Klemme5.setObjectName("Klemme5")
        self.Klemme6 = QtWidgets.QPushButton(self.centralwidget)
        self.Klemme6.setEnabled(False)
        self.Klemme6.setGeometry(QtCore.QRect(900, 530, 416, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Klemme6.setFont(font)
        self.Klemme6.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.134 rgba(7, 255, 44, 255), stop:0.608939 rgba(255, 241, 87, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 15;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 400px;\n"
"max-width: 400px;\n"
"min-height: 44px;\n"
"max-height: 44\n"
"px;\n"
"}")
        self.Klemme6.setObjectName("Klemme6")
        self.Loeschen = QtWidgets.QPushButton(self.centralwidget)
        self.Loeschen.setEnabled(False)
        self.Loeschen.setGeometry(QtCore.QRect(40, 610, 416, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Loeschen.setFont(font)
        self.Loeschen.setStyleSheet("QPushButton {\n"
"color: white;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 53, 56, 255), stop:1 rgba(255, 165, 101, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 15;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 400px;\n"
"max-width: 400px;\n"
"min-height: 44px;\n"
"max-height: 44px;\n"
"}")
        self.Loeschen.setObjectName("Loeschen")
        self.AllesLoeschen = QtWidgets.QPushButton(self.centralwidget)
        self.AllesLoeschen.setEnabled(False)
        self.AllesLoeschen.setGeometry(QtCore.QRect(900, 610, 416, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.AllesLoeschen.setFont(font)
        self.AllesLoeschen.setStyleSheet("QPushButton {\n"
"color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 53, 56, 255), stop:1 rgba(255, 165, 101, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 15;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 400px;\n"
"max-width: 400px;\n"
"min-height: 44px;\n"
"max-height: 44px;\n"
"}")
        self.AllesLoeschen.setObjectName("AllesLoeschen")
        self.SendenAnRobo = QtWidgets.QPushButton(self.centralwidget)
        self.SendenAnRobo.setEnabled(False)
        self.SendenAnRobo.setGeometry(QtCore.QRect(470, 610, 416, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.SendenAnRobo.setFont(font)
        self.SendenAnRobo.setStyleSheet("QPushButton {\n"
"color: white;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(29, 90, 232, 255), stop:1 rgba(62, 193, 178, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 15;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 400px;\n"
"max-width: 400px;\n"
"min-height: 44px;\n"
"max-height: 44px;\n"
"}")
        self.SendenAnRobo.setObjectName("SendenAnRobo")
        self.label_command = QtWidgets.QLabel(self.centralwidget)
        self.label_command.setGeometry(QtCore.QRect(580, 30, 621, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_command.setFont(font)
        self.label_command.setObjectName("label_command")
        self.Absenden = QtWidgets.QPushButton(self.centralwidget)
        self.Absenden.setGeometry(QtCore.QRect(580, 10, 266, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Absenden.setFont(font)
        self.Absenden.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.00558659 rgba(59, 59, 59, 255), stop:1 rgba(166, 166, 166, 255));\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-style: solid;\n"
"border-radius: 8;\n"
"padding: 3px;\n"
"font-size: 16\n"
"px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 250px;\n"
"max-width: 250px;\n"
"min-height: 25px;\n"
"max-height: 25px;\n"
"}")
        self.Absenden.setObjectName("Absenden")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 90, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QTabBar::tab{ \n"
"height: 50px; width:148px; \n"
"background-color: rgb(232, 232, 232);\n"
"color: rgb(0, 0, 0);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(91, 91, 91);\n"
"border-radius: 0;\n"
"padding: 3px;\n"
"font-size: 24px;\n"
"}\n"
"\n"
"QTabBar::tab:hover{\n"
"    border-top-color: #1D2A32;\n"
"    border-color: #40494E;\n"
"    color: black;\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background-color: rgb(5, 33, 22);\n"
"    color: rgb(255, 255, 255);\n"
"          }\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName("menubar")
        self.menuOMRON_TM12_Best_ckung = QtWidgets.QMenu(self.menubar)
        self.menuOMRON_TM12_Best_ckung.setObjectName("menuOMRON_TM12_Best_ckung")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuOMRON_TM12_Best_ckung.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "HW1"))
        self.label_6.setText(_translate("MainWindow", "Hutschiene Waagerecht 2 wird bestückt."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "HW2"))
        self.label_7.setText(_translate("MainWindow", "Hutschiene Waagerecht 3 wird bestückt."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "HW3"))
        self.label_8.setText(_translate("MainWindow", "Hutschiene Waagerecht 4 wird bestückt."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "HW4"))
        self.label_9.setText(_translate("MainWindow", "Hutschiene Senkrecht 1 wird bestückt."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "HS1"))
        self.label_10.setText(_translate("MainWindow", "Hutschiene Senkrecht 2 wird bestückt."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "HS2"))
        self.label_11.setText(_translate("MainWindow", "Hutschiene Senkrecht 3 wird bestückt."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "HS3"))
        self.label_12.setText(_translate("MainWindow", "Hutschiene Senkrecht 4 wird bestückt."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "HS4"))
        self.maxKlemmenHutschiene.setText(_translate("MainWindow", "Klemmenlimit pro Hutschiene:"))
        self.label_2.setText(_translate("MainWindow", "Anzahl möglicher Hutschienen:"))
        self.label.setText(_translate("MainWindow", "Anzahl möglicher Klemmen:"))
        self.AnzahlKlemme3.setText(_translate("MainWindow", "Anzahl STS 2.5 T:"))
        self.setAnzahlKlemme6.setText(_translate("MainWindow", "0"))
        self.setAnzahlKlemme1.setText(_translate("MainWindow", "0"))
        self.setAnzahlKlemme4.setText(_translate("MainWindow", "0"))
        self.AnzahlKlemme4.setText(_translate("MainWindow", "Anzahl ST 2.5 T PE:"))
        self.AnzahlKlemme2.setText(_translate("MainWindow", "Anzahl ST 2.5:"))
        self.setAnzahlKlemme5.setText(_translate("MainWindow", "0"))
        self.setAnzahlKlemme3.setText(_translate("MainWindow", "0"))
        self.AnzahlKlemme6.setText(_translate("MainWindow", "Anzahl STS 2.5 T PE:"))
        self.AnzahlKlemme5.setText(_translate("MainWindow", "Anzahl ST 2.5 PE:"))
        self.setAnzahlKlemme2.setText(_translate("MainWindow", "0"))
        self.AnzahlKlemme1.setText(_translate("MainWindow", "Anzahl ST 2.5 T:"))
        self.AnzahlGesamt.setText(_translate("MainWindow", "Anzahl auf dieser Hutschiene:"))
        self.label_3.setText(_translate("MainWindow", "Anzahl auf Montageplatte:"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.setAnzahlGesamt.setText(_translate("MainWindow", "0"))
        self.Klemme1.setText(_translate("MainWindow", "ST 2.5 TWIN"))
        self.Klemme2.setText(_translate("MainWindow", "ST 2.5"))
        self.Klemme3.setText(_translate("MainWindow", "STS 2.5 TWIN"))
        self.Klemme4.setText(_translate("MainWindow", "ST 2.5 TWIN PE"))
        self.Klemme5.setText(_translate("MainWindow", "ST 2.5 PE"))
        self.Klemme6.setText(_translate("MainWindow", "STS 2.5 TWIN PE"))
        self.Loeschen.setText(_translate("MainWindow", "gewählte Hutschiene löschen"))
        self.AllesLoeschen.setText(_translate("MainWindow", "alle Hutschienen löschen"))
        self.SendenAnRobo.setText(_translate("MainWindow", "Übertragung starten"))
        self.label_command.setText(_translate("MainWindow", "Kommandozeile"))
        self.Absenden.setText(_translate("MainWindow", "Bestätigen"))
        self.label_5.setText(_translate("MainWindow", "Hutschiene Waagerecht 1 wird bestückt."))
        self.menuOMRON_TM12_Best_ckung.setTitle(_translate("MainWindow", "OMRON TM12 Bestückung"))
